// Regenerates the launch assets FROM THE REAL GAME (DESIGN §8, PWA): the app icons and the social card are
// rendered by the game's own renderer in a real (headless) Chrome over CDP, never drawn separately.
//
//   node tools/launch-assets.mjs                     # everything, writing into the repo root
//   node tools/launch-assets.mjs --only=icons        # icon-192.png icon-512.png icon-maskable-512.png
//                                                    #   apple-touch-icon.png favicon-32.png favicon.svg
//   node tools/launch-assets.mjs --only=og [--seed=N] [--zoom=Z] [--focus=windmill|keep|<region id>]
//   node tools/launch-assets.mjs --preview=screenshots/game    # also write launch-*.png previews there
//   node tools/launch-assets.mjs --out=some/dir                # write the assets elsewhere (default: the repo root)
//
// Icons: tools/launch/launchArt.js composes the game's own `drawTileBase` (the region), `drawSettlement` (the keep),
// `drawBanner` (the player's banner) and the ocean gradient into one bold mark; every size is rendered at its own
// resolution, and launchArt.js's contact sheet shows them at 1:1 (the 48 px one must still read) with the maskable
// safe circle. Favicon sizes (32 px, and the 64 px PNG inside favicon.svg) use the simplified 'mini' mark: no detailed keep,
// a big banner on a deep-azure hex. og.png: a hero shot of a lush level-III realm (keep, windmills, banners, caravans,
// smoke, sea) taken with the live renderer at 1200x630, with the wordmark laid over it.
// On this machine: CHROME_PATH="/c/Program Files/Google/Chrome/Application/chrome.exe" (defaulted).
import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

if (!process.env.CHROME_PATH && process.platform === 'win32') {
  process.env.CHROME_PATH = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
}
const { launch } = await import('./cdp.js');

const flags = Object.fromEntries(process.argv.slice(2).filter((a) => a.startsWith('--')).map((a) => {
  const [k, ...v] = a.slice(2).split('=');
  return [k, v.join('=') || 'true'];
}));
const ROOT = fileURLToPath(new URL('..', import.meta.url));
const OUT = flags.out || ROOT;
const PREVIEW = flags.preview || null;
const ONLY = flags.only || 'all';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Our own dev server on a private port (unless --url points at one already running).
let server = null;
let BASE = flags.url || null;
if (!BASE) {
  const port = 22000 + Math.floor(Math.random() * 20000);
  server = spawn(process.execPath, ['tools/serve.js', `--port=${port}`], { stdio: 'ignore', cwd: ROOT });
  BASE = `http://localhost:${port}`;
  for (let i = 0; i < 60; i++) {
    try { if ((await fetch(`${BASE}/`)).ok) break; } catch { /* not up yet */ }
    await sleep(100);
  }
}
const stop = () => { if (server) { server.kill(); server = null; } };
process.on('exit', stop);

await mkdir(OUT, { recursive: true });
if (PREVIEW) await mkdir(PREVIEW, { recursive: true });
const save = async (dir, name, base64) => {
  await writeFile(join(dir, name), Buffer.from(base64, 'base64'));
  console.log(`  wrote ${join(dir, name)}`);
};

// ---- icons ---------------------------------------------------------------------------------------------------------
async function icons() {
  console.log('icons: rendering with the game renderer');
  const page = await launch({ url: 'about:blank', width: 800, height: 600 });
  await page.send('Emulation.setDeviceMetricsOverride', { width: 800, height: 600, deviceScaleFactor: 1, mobile: false });
  await page.goto(`${BASE}/index.html?dev=1&seed=7`);
  for (let i = 0; i < 100; i++) { if (await page.eval(() => !!window.__hd)) break; await sleep(100); }
  const render = (size, kind) => page.eval(async (s, k) => {
    const m = await import(new URL('tools/launch/launchArt.js', document.baseURI).href);
    return m.toPngBase64(m.renderIcon(s, { kind: k }));
  }, size, kind);

  await save(OUT, 'icon-192.png', await render(192, 'any'));
  await save(OUT, 'icon-512.png', await render(512, 'any'));
  await save(OUT, 'icon-maskable-512.png', await render(512, 'maskable'));
  await save(OUT, 'apple-touch-icon.png', await render(180, 'apple'));
  await save(OUT, 'favicon-32.png', await render(32, 'mini')); // the simplified favicon mark: no keep, a big banner
  // favicon.svg keeps its name (manifest and index.html point at it): a vector wrapper around the game-rendered 64 px
  // mark, so browsers that prefer SVG favicons still show the real art.
  const png64 = await render(64, 'mini');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="Hex Dominion">\n`
    + `  <!-- Generated by tools/launch-assets.mjs from the game's own renderer: do not edit by hand. -->\n`
    + `  <image width="64" height="64" href="data:image/png;base64,${png64}"/>\n</svg>\n`;
  await writeFile(join(OUT, 'favicon.svg'), svg);
  console.log(`  wrote ${join(OUT, 'favicon.svg')}`);
  if (PREVIEW) {
    const sheet = await page.eval(async () => {
      const m = await import(new URL('tools/launch/launchArt.js', document.baseURI).href);
      return m.renderSheet();
    });
    await save(PREVIEW, 'launch-icons.png', sheet.replace(/^data:image\/png;base64,/, ''));
  }
  await page.close();
}

// ---- the social card (og.png, 1200x630) ---------------------------------------------------------------------------
// A real frame of the live game: a fresh realm widened with the dev hooks, nine hours of tenure (prosperity III: windmills,
// paving, orchards, market awnings), the ambient layer at full quality, the camera on the lushest keep-and-windmill corner
// with sea and fog at its edges, the UI hidden, the wordmark laid over it. Rendered at 2x and downscaled for clean edges.
async function og(seed, previewName) {
  console.log(`og: seed ${seed}`);
  const W = 1200;
  const H = 630;
  const page = await launch({ url: 'about:blank', width: W, height: H });
  await page.send('Emulation.setDeviceMetricsOverride', { width: W, height: H, deviceScaleFactor: 2, mobile: false });
  await page.goto(`${BASE}/index.html?dev=1&seed=${seed}`);
  for (let i = 0; i < 100; i++) { if (await page.eval(() => !!window.__hd && window.__hd.scene === 'title')) break; await sleep(100); }
  await page.eval(() => { window.__hd.hideDev(true); window.__hd.startNewRealm(); });
  await sleep(3800);
  const regions = Number(flags.regions || 10);
  await page.eval((n) => {
    const hd = window.__hd;
    hd.state.settings.hints = false;
    hd.state.tutorial.done = true;
    hd.state.metFactions = hd.world.factions.map((_, i) => i); // no leader banner over the picture
    hd.lockAmbientQuality(1);
    hd.conquerRegions(n);
    hd.advanceTenure(9);
  }, regions);
  await sleep(7500); // the chunks re-bake, the mists settle
  const hero = await page.eval(async () => {
    const m = await import(new URL('tools/launch/launchArt.js', document.baseURI).href);
    return m.pickHero(window.__hd);
  });
  if (!hero) throw new Error('no owned region with a windmill: raise --regions');
  console.log(`  focus: region ${hero.regionId} at (${hero.x.toFixed(1)}, ${hero.y.toFixed(1)}) score ${hero.score.toFixed(2)} ${JSON.stringify(hero.parts, (k, v) => (typeof v === 'number' ? +v.toFixed(2) : v))}`);
  const zoom = Number(flags.zoom || 46);
  // The lush corner sits right of centre and high, so the wordmark has the lower left to itself.
  const fx = flags.x != null ? Number(flags.x) : hero.x - Number(flags.dx ?? 3.2);
  const fy = flags.y != null ? Number(flags.y) : hero.y + Number(flags.dy ?? 2.4);
  await page.eval((x, y, z) => window.__hd.camera.flyTo({ x, y, zoom: z }, 1), fx, fy, zoom);
  await sleep(6500); // caravans fill the roads, smoke rises, sails turn
  await page.eval(() => {
    window.__hd.hideUI(true);
    const tag = document.createElement('div');
    tag.id = 'launch-wordmark';
    tag.style.cssText = 'position:fixed;left:0;bottom:0;padding:54px 64px 40px 52px;z-index:99;pointer-events:none;'
      + 'background:radial-gradient(ellipse at 0% 100%, rgba(8,16,30,0.78) 0%, rgba(8,16,30,0.55) 42%, rgba(8,16,30,0) 72%);';
    tag.innerHTML = '<div style="font:800 76px/1 Cinzel,Georgia,serif;letter-spacing:.07em;color:#f5c451;'
      + 'text-shadow:0 3px 0 #6b4a0e,0 10px 34px rgba(0,0,0,.6)">HEX DOMINION</div>'
      + '<div style="margin-top:12px;font:700 25px/1.25 Nunito,system-ui,sans-serif;letter-spacing:.04em;color:#f3ead7;'
      + 'text-shadow:0 2px 10px rgba(0,0,0,.7)">Conquer a living hex continent. Idle conquest, real-time battles.</div>';
    document.body.appendChild(tag);
  });
  await sleep(900);
  const shot = await page.send('Page.captureScreenshot', { format: 'png' });
  const png = await page.eval(async (b64, w, h) => {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    const bmp = await createImageBitmap(new Blob([bytes], { type: 'image/png' }));
    // 2x -> 1x in two halvings-worth of smoothing: crisp, no aliasing on the roofs and sails
    const c = new OffscreenCanvas(w, h);
    const g = c.getContext('2d');
    g.imageSmoothingEnabled = true;
    g.imageSmoothingQuality = 'high';
    g.drawImage(bmp, 0, 0, w, h);
    const blob = await c.convertToBlob({ type: 'image/png' });
    const buf = new Uint8Array(await blob.arrayBuffer());
    let out = '';
    for (let i = 0; i < buf.length; i += 0x8000) out += String.fromCharCode(...buf.subarray(i, i + 0x8000));
    return btoa(out);
  }, shot.data, W, H);
  await page.close();
  return png;
}

if (ONLY === 'all' || ONLY === 'icons') await icons();
if (ONLY === 'og') {
  const seeds = String(flags.seed || '7').split(',');
  for (const seed of seeds) {
    const png = await og(seed);
    if (seeds.length > 1 || flags.explore) await save(PREVIEW || OUT, `launch-og-seed${seed}.png`, png);
    else await save(OUT, 'og.png', png);
    if (PREVIEW && seeds.length === 1 && !flags.explore) await save(PREVIEW, 'launch-og.png', png);
  }
}
if (ONLY === 'all') {
  const png = await og(flags.seed || '7');
  await save(OUT, 'og.png', png);
  if (PREVIEW) await save(PREVIEW, 'launch-og.png', png);
}
stop();
console.log('done');
process.exit(0);
