// Writes the boot-critical module graph into index.html as <link rel="modulepreload"> tags (PLAN-PHASE8 §8A). Still no build step at runtime: this
// only edits the page's <head>, between two markers, so the browser starts fetching every module the boot needs at once instead of discovering them
// level by level (main.js -> its imports -> theirs ...: four or five round trips on a slow phone network).
//
//   node tools/modulepreload.mjs          # rewrite the block in index.html
//   node tools/modulepreload.mjs --check  # exit 1 if the block is out of date (tools/check.mjs runs this)
//
// The graph is every module main.js reaches through STATIC imports. Dynamic import() targets are deliberately left out (they load when needed).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = join(ROOT, 'game', 'main.js');
const START = '<!-- modulepreload:start (generated by tools/modulepreload.mjs; do not edit by hand) -->';
const END = '<!-- modulepreload:end -->';
// import x from './a.js'; import { a,\n b } from "./b.js"; import './c.js'; export { y } from './d.js'
const STATIC = /(?:^|\n)[ \t]*(?:import|export)[ \t\n]+(?:[^'";]*?[ \t\n]from[ \t\n]*)?['"](\.{1,2}\/[^'"]+)['"]/g;

/** Every module reachable from `entry` by static imports, in depth-first post-order (dependencies before dependents). */
export function staticGraph(entry = ENTRY) {
  const seen = new Set();
  const order = [];
  const visit = (file) => {
    if (seen.has(file)) return;
    seen.add(file);
    const src = readFileSync(file, 'utf8'); // not comment-stripped: a "// game/scenes/*" line would open a fake block comment
    for (const m of src.matchAll(STATIC)) visit(resolve(dirname(file), m[1]));
    order.push(file);
  };
  visit(entry);
  return order;
}

const DYNAMIC = /\bimport\(\s*['"](\.{1,2}\/[^'"]+)['"]\s*\)/g;
/** Modules loaded later by import() (and what they import that the boot does not): not preloaded, but listed for the service worker's precache. */
export function lazyModules(boot = staticGraph()) {
  const have = new Set(boot);
  const out = [];
  const queue = [...boot];
  while (queue.length) {
    const file = queue.shift();
    for (const m of readFileSync(file, 'utf8').matchAll(DYNAMIC)) {
      for (const dep of staticGraph(resolve(dirname(file), m[1]))) {
        if (have.has(dep)) continue;
        have.add(dep);
        out.push(dep);
        queue.push(dep);
      }
    }
  }
  return out;
}

const rel = (f) => `./${relative(ROOT, f).split('\\').join('/')}`;
export function preloadBlock() {
  const boot = staticGraph();
  const lines = boot.filter((f) => f !== ENTRY).map((f) => `<link rel="modulepreload" href="${rel(f)}">`);
  // the service worker caches these too (index.html adds them to its precache list), so a lazily loaded panel works offline after one visit
  lines.push(`<meta name="hd-lazy" content="${lazyModules(boot).map(rel).join(' ')}">`);
  return [START, ...lines, END].join('\n');
}

function main() {
  const htmlPath = join(ROOT, 'index.html');
  const html = readFileSync(htmlPath, 'utf8');
  const block = preloadBlock();
  const a = html.indexOf(START.slice(0, 30));
  const b = html.indexOf(END);
  let next;
  if (a >= 0 && b > a) next = html.slice(0, a) + block + html.slice(b + END.length);
  // first time: after the inline script that raises the resource-timing buffer (250 entries by default: 246 preloads filled it before it was raised, and
  // the service worker's first-visit precache list, read from those entries, lost the late modules)
  else next = html.replace('</script>\n</head>', `</script>\n${block}\n</head>`);
  const count = block.split('\n').length - 3;
  if (process.argv.includes('--check')) {
    // line-ending-insensitive: a Windows (CRLF) checkout holds the same content as CI's LF one (Phase 10B)
    const lf = (t) => t.replace(/\r\n/g, '\n');
    if (lf(next) !== lf(html)) { console.error(`index.html: the modulepreload block is out of date (${count} modules now): run node tools/modulepreload.mjs`); process.exit(1); }
    console.log(`index.html: modulepreload block up to date (${count} modules)`);
    return;
  }
  writeFileSync(htmlPath, next);
  console.log(`index.html: ${count} modulepreload links written`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
